# Master playbook to configure and run the database and application servers
# Pulls in playbooks for both the database and application servers
- name: Configure and run database and application servers
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Include MongoDB playbook
      include_tasks: ansible-configure-and-run-db.yaml

    - name: Include App playbook
      include_tasks: ansible-configure-and-run-app-npm.yaml
