# Ansible playbook to install MongoDB 7.0 on a Ubuntu 22.04 server

# all plays start with ---
---
# name of the play
- name: install db dependencies for sparta app
  # where to run this play
  hosts: db
  # get comprehensive facts on the host?
  gather_facts: yes
  # provide sudo access for the play?
  become: true


  # instructions for the play are the tasks
  tasks:
  # apt update
  - name: Update apt cache
    apt:
      update_cache: yes
  # apt upgrade
  - name: Upgrade all packages
    apt:
      upgrade: dist

  # install curl and gnupg
  - name: Install Curl and GnuPG
    apt:
      pkg: 
        - curl
        - gnupg
      state: present


  # remove existing MongoDB GPG key (if any)
  - name: Remove existing MongoDB GPG key (if any)
    file:
      path: /usr/share/keyrings/mongodb-server-7.0.gpg
      state: absent

  # download MongoDB GPG key and convert to keyring format
  - name: Import MongoDB public GPG key and convert to keyring format
    shell: |
      curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | \
      gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor --yes
    args:
      creates: /usr/share/keyrings/mongodb-server-7.0.gpg

  # create MongoDB APT source list file
  - name: Create MongoDB APT source list file
    copy:
      dest: /etc/apt/sources.list.d/mongodb-org-7.0.list
      content: |
        deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse
      mode: '0644'

  # ensure the MongoDB APT source list file exists
  - name: Reload APT package database
    apt:
      update_cache: yes

  # install MongoDB 7.0.6 and related packages
  - name: Install MongoDB 7.0.6 and related packages
    apt:
      name:
        - mongodb-org=7.0.6
        - mongodb-org-database=7.0.6
        - mongodb-org-server=7.0.6
        - mongodb-org-shell=7.0.6
        - mongodb-org-mongos=7.0.6
        - mongodb-org-tools=7.0.6
        - mongodb-mongosh
        - mongodb-org-database-tools-extra=7.0.6
      state: present
      update_cache: no
      force: yes
      allow_unauthenticated: no
      install_recommends: yes
    environment:
      DEBIAN_FRONTEND: noninteractive

# enable mongodb service to start on boot and start it now
  - name: Enable MongoDB service to start on boot
    systemd:
      name: mongod
      enabled: yes
      state: started
