# starts with ---
---
# name of the play
- name: install app dependencies and run app
  # where to run this play
  hosts: web
  # get comprehensive facts on the host?
  gather_facts: yes
  # provide sudo access for the play?
  become: true

  # instructions in the play are the tasks
  # task 1: install nginx on target node
  tasks:
  # apt update
  - name: Update apt cache
    apt:
      update_cache: yes

  # apt upgrade
  - name: Upgrade all packages
    apt:
      upgrade: dist

  # install curl
  - name: Install Curl, unzip and nginx
    apt:
      pkg:
        - curl
        - unzip
        - nginx
      state: present

 # curl NodeJS 20 repository
  - name: Download NodeJS 20 repo
    shell: curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    args:
      executable: /bin/bash

  # install NodeJS
  - name: Install NodeJS 20
    apt:
      name: nodejs
      state: present

  # copy app folder from Controller node, into Target node (could change this to be a git clone)
  - name: Copy app zip from Controller node
    copy:
      src: /home/ubuntu/nodejs20-sparta-test-app.zip
      dest: /home/ubuntu/

  # unzip app 
  - name: Unzip the app
    unarchive:
      src: /home/ubuntu/nodejs20-sparta-test-app.zip
      dest: /home/ubuntu/
    args:
      # stops Ansible from trying to create a directory if unzip has already happened
      creates: /home/ubuntu/app/

  # Allow port 3000
  - name: Allow port 3000 via TCP
    ufw:
      rule: allow
      port: '3000'
      proto: tcp

  # install npm dependencies
  - name: Install npm dependencies
    community.general.npm:
      path: /home/ubuntu/app/

  # install pm2
  - name: Install pm2 globally
    npm:
      name: pm2
      global: yes
  # run app with pm2
  - name: Start app with pm2
    command: pm2 start app.js
    args:
      chdir: /home/ubuntu/app/
  


  # Configure nginx to act as reverse proxy for app port 3000, copy over correct nginx config file and restart nginx, presume file is called ''
  # Remove default NGINX config file
  - name: Remove old nginx config file
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  # Create NGINX reverse proxy config
  - name: Configure NGINX reverse proxy
    copy:
      dest: /etc/nginx/sites-available/node_app
      content: |
        server {
            listen 80;

            location / {
                proxy_pass http://localhost:3000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
            }
        }

  # Enable the new NGINX config
  - name: Enable NGINX reverse proxy config
    file:
      src: /etc/nginx/sites-available/node_app
      dest: /etc/nginx/sites-enabled/node_app
      state: link
      force: yes
  # Restart NGINX to apply changes
  - name: Restart NGINX
    service:
      name: nginx
      state: restarted
...

